dist: trusty
sudo: required
language: cpp

notifications:
 email: false

os:
 - linux
 - osx

compiler:
 - gcc
 - clang

 #TODO: Get C++17 support

script:
 - mkdir build
 - cd build
 - cmake ..
 - cmake --build . -- -j4
 - ctest
