dist: trusty
sudo: required
language: cpp

notifications:
 email: false

os:
 - linux
 - osx

compiler:
 - gcc
 - clang

script:
 - mkdir build
 - cd build
 - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake ..
 - cmake --build . -- -j4
 - echo "Building finished......."
 - echo "Running unit test......."
 - ctest
