dist: trusty
sudo: required
language: cpp

notifications:
 email: false

matrix:
  include:
    # GCC 6
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc6 && CXX=g++-6"
    # GCC 7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    # Clang 4.0
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    # Clang 4.9
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
  - eval "${MATRIX_EVAL}"

script:
 - mkdir build
 - cd build
 - cmake ..
 - cmake --build . -- -j4
 - ctest
